/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorContrractSol from "./GovernorContrract.sol";
export { Timeock__factory } from "./Timeock__factory";
