/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorContrractSol from "./GovernorContrract.sol";
export type { governorContrractSol };
export type { Timeock } from "./Timeock";
